# Pytorch Basics 
<h2>Introduction</h2>
As we've seen we can use numpy to create single layer neural networks by calculating the gradients by hand and hard coding them and training them via GD. But what if we want to create larger and more complicated networks? What if we want to use complicated and fancy loss functions or use huge datasets and train with more complicated training regimes?! And what about training on GPUs.......<br>
That's a lot to try and work out EVERY time we want to try something new!! Lucky for us there are a number of Deep learning frameworks that can do much of the heavy lifting for us!<br>
For this unit we will be using Pytorch, a hugely powerful and widely used Deep Learning framework that lets us do all of the above and MORE

In [1]:
import torch
import torchvision
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt

<h3> The Pytorch Tensor </h3>
As we've already explored the "Tensor" is a useful concept and is very useful in Machine Learning, however you probably noticed in Numpy that our "Tensors" are called "Arrays", but now we are in Pytorch this is no more!!<br>
Let's do a recap of Numpy arrays and how similar they are to Pytorch tensors.

In [2]:
# Create some "Matrices" as lists of lists  

# 3x3
W = [[1, 1, 1],
     [1.5, 1.5, 1.5],
     [2, 2, 2]]

# 3x1
x = [[6], [7], [8]]
# 3x1
b = [[1], [1], [1]]

# Variable to store output
# 3x1
y = [[0], [0], [0]]

# We can transform our list of lists into a "numpy array" by using the function "array"
W_np = np.array(W)

x_np = np.array(x)

# Lets use the function "ones" to create an array of ones!
b_np = np.ones((3, 1))

# Lets now compute Wx + b using these numpy variables!
output = np.matmul(W_np, x_np) + b_np

# Print out the result
print("Output:\n", output)
print("Output shape:\n", output.shape)

Output:
 [[22. ]
 [32.5]
 [43. ]]
Output shape:
 (3, 1)


In [3]:
# We can transform our list of lists into a "torch tensor" by using the function "FloatTensor"
# Note: here we've specified the datatype of the tensor, a 32bit "float" you can also just use the function "tensor"
# But this will inherit the datatype of the array given, to ensure the data-types are the same
# (and we can perform the wanted operations) we use "FloatTensor"

W_torch = torch.FloatTensor(W)

x_torch = torch.FloatTensor(x)

# Lets use the function "ones" to create an array of ones!
b_torch = torch.ones(3, 1)

# Lets now compute Wx + b using these numpy variables!
output = torch.matmul(W_torch, x_torch) + b_torch

# Print out the result
print("Output:\n", output)
print("Output shape:\n", output.shape)

Output:
 tensor([[22.0000],
        [32.5000],
        [43.0000]])
Output shape:
 torch.Size([3, 1])


Wow! Numpy and Pytorch are remarkably similar, though this is no coincidence! The creators of Pytorch did this intentionally to make it easy to transfer existing skills in Numpy (a Python library that everyone uses - has its origins back in 1995!!) to Pytorch. To aid this transfer there are even functions that can transfer Pytorch tensors to Numpy arrays and back!

In [4]:
# Create a random Numpy array
np_array = np.random.random((3, 4))
print("Numpy array:\n", np_array)

# Convert to Pytorch tensor
torch_tensor = torch.FloatTensor(np_array)
print("Pytorch tensor:\n", torch_tensor)

# Convert back to a Numpy array!
np_array2 = torch_tensor.numpy()
print("Numpy array:\n", np_array2)

Numpy array:
 [[0.30607562 0.1963901  0.92569213 0.2113765 ]
 [0.3595142  0.53641871 0.59839116 0.40926204]
 [0.36449702 0.34376457 0.61977947 0.9776756 ]]
Pytorch tensor:
 tensor([[0.3061, 0.1964, 0.9257, 0.2114],
        [0.3595, 0.5364, 0.5984, 0.4093],
        [0.3645, 0.3438, 0.6198, 0.9777]])
Numpy array:
 [[0.3060756  0.1963901  0.92569214 0.2113765 ]
 [0.3595142  0.53641874 0.5983912  0.40926203]
 [0.364497   0.34376457 0.61977947 0.9776756 ]]


<h1>On to Pytorch!</h1>
Let's further explore Pytorch and it's similarities to Numpy and then see what new functionalities it brings to the table!!
<h3> Basic Element-wise Operations </h3>
Let's quickly go back over some basics using Pytorch

In [5]:
# Lets create a 2D Tensor using torch.rand
y = torch.rand(4, 5)
# This will create a "Vector" of numbers from 0 to 1
print("Our 1D Tensor:\n",y)

# We can perform normal python scalar arithmetic on Torch tensors
print("\nScalar Multiplication:\n",y * 10)
print("Addition and Square:\n",(y + 1)**2)
print("Addition:\n",y + y)
print("Addition and division:\n",y / (y + 1))

# We can use a combination of Torch functions and normal python arithmetic
print("\nPower and square root:\n",torch.sqrt(y**2))

# Torch tensors are objects and have functions
print("\nY -\n Min:%.2f\n Max:%.2f\n Standard Deviation:%.2f\n Sum:%.2f" %(y.min(), y.max(), y.std(), y.sum()))

Our 1D Tensor:
 tensor([[0.9985, 0.7946, 0.3844, 0.8575, 0.3624],
        [0.6194, 0.3968, 0.1972, 0.3821, 0.4868],
        [0.4188, 0.6942, 0.1648, 0.8704, 0.1313],
        [0.9882, 0.5286, 0.4773, 0.7887, 0.3205]])

Scalar Multiplication:
 tensor([[9.9854, 7.9459, 3.8442, 8.5745, 3.6242],
        [6.1941, 3.9676, 1.9715, 3.8209, 4.8681],
        [4.1876, 6.9416, 1.6480, 8.7039, 1.3126],
        [9.8820, 5.2863, 4.7733, 7.8872, 3.2050]])
Addition and Square:
 tensor([[3.9941, 3.2206, 1.9166, 3.4501, 1.8562],
        [2.6225, 1.9509, 1.4332, 1.9102, 2.2106],
        [2.0129, 2.8702, 1.3568, 3.4984, 1.2797],
        [3.9529, 2.3367, 2.1825, 3.1995, 1.7437]])
Addition:
 tensor([[1.9971, 1.5892, 0.7688, 1.7149, 0.7248],
        [1.2388, 0.7935, 0.3943, 0.7642, 0.9736],
        [0.8375, 1.3883, 0.3296, 1.7408, 0.2625],
        [1.9764, 1.0573, 0.9547, 1.5774, 0.6410]])
Addition and division:
 tensor([[0.4996, 0.4428, 0.2777, 0.4616, 0.2660],
        [0.3825, 0.2841, 0.1647, 0.2765, 0.3274]

### Tensor operations

In [ ]:
# Create two 3D Tensors
tensor_1 = torch.rand(3,3,3)
tensor_2 = torch.rand(3,3,3)

# Add the 2 Tensors
print("Addition:\n",tensor_1 + tensor_2)

# We cannot perform a normal "matrix" multiplication on a 3D tensor
# But we can treat the 3D tensor as a "batch" (like a stack) of 2D tensors
# And perform normal matrix multiplication independantly on each pair of 2D matricies
print("Batch Multiplication:\n", torch.bmm(tensor_1, tensor_2))